// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjv50A9DLwP-ZG7SkrbJHOecyR27hXNF0',
    appId: '1:200431842557:web:84a24991b7ddcba7aefa94',
    messagingSenderId: '200431842557',
    projectId: 'aniview-app',
    authDomain: 'aniview-app.firebaseapp.com',
    storageBucket: 'aniview-app.firebasestorage.app',
    measurementId: 'G-4W3DWXKJ6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGwjpK11zym4zhkgN64WwJMPwiX-xhe74',
    appId: '1:200431842557:android:782d634306c3c861aefa94',
    messagingSenderId: '200431842557',
    projectId: 'aniview-app',
    storageBucket: 'aniview-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEyvIw3IoTfxBlLM0McHa9JPkaYZu5O-8',
    appId: '1:200431842557:ios:2daf467602e94b81aefa94',
    messagingSenderId: '200431842557',
    projectId: 'aniview-app',
    storageBucket: 'aniview-app.firebasestorage.app',
    iosClientId: '200431842557-gleu6gr7jj39qvromgbr898dl3qp9ce0.apps.googleusercontent.com',
    iosBundleId: 'com.example.aniviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEyvIw3IoTfxBlLM0McHa9JPkaYZu5O-8',
    appId: '1:200431842557:ios:2daf467602e94b81aefa94',
    messagingSenderId: '200431842557',
    projectId: 'aniview-app',
    storageBucket: 'aniview-app.firebasestorage.app',
    iosClientId: '200431842557-gleu6gr7jj39qvromgbr898dl3qp9ce0.apps.googleusercontent.com',
    iosBundleId: 'com.example.aniviewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjv50A9DLwP-ZG7SkrbJHOecyR27hXNF0',
    appId: '1:200431842557:web:fecd09f84c35a5efaefa94',
    messagingSenderId: '200431842557',
    projectId: 'aniview-app',
    authDomain: 'aniview-app.firebaseapp.com',
    storageBucket: 'aniview-app.firebasestorage.app',
    measurementId: 'G-6QT887S957',
  );
}
